all:   cellular_automaton.c cellular_automaton.h ../matrix_of_cells/matrix_of_cells.c test.c ../rules/rules.c ../txt_input/txt_input.c
	   @gcc cellular_automaton.c ../matrix_of_cells/matrix_of_cells.c test.c ../rules/rules.c ../txt_input/txt_input.c -std=c99	
	   @./a.out 

